---

- hosts: all
  become: true
  tasks:

  - name: Removing apache2 package & php support for apache2
    apt:
      name:
         - apache2
         - libapache2-mod-php 
      state: absent
      update_cache: yes

