---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (CentOS)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"
  
  - name: install updates (ubuntu)
    tags: always
    apt:
      upgrage: dist
      update_cache: yes
    when: ansible_distribution == "ubuntu"

- hosts: web_servers
  become: true
  tasks:
  
  - name: install apache & php for ubuntu web server
    tags: apache, apache2, ubuntu
    apt:
      name:
         - apache2
         - libapache2-mod-php
      status: latest
    when: ansible_distribution == "ubuntu"

  - name: Copy default html file required for the site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

  - name: install apache & php for CentOS web server
    tags: php, httpd, CentOS
    apt:
      name:
         - httpd
         - php
      status: latest
    when: ansible_distribution == "CentOS"

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (CentOS)
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install mariadb package (ubuntu)
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    package:
         name: samba
         state: latest
