---

- hosts: all
  become: true
  tasks:

  - name: Install Unzip
    package: 
       name: unzip

  - name: Install Terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.3.6/terraform_1.3.6_linux_386.zip
      dest: /user/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root
